disp('Incomplete Test')
return;
      
      
      self.msg_sizes.bsize = 1;     % Size of a bit messages
      self.msg_sizes.dsize = 8;     % Size of a double messages
      self.msg_sizes.vsize = 32767; % Size of a large varible messages
      
      tsat_msgs_temp = {...
          {'ReadAck',{2, self.msg_sizes.bsize, 'ReadAckMesg', 'Set run mode'}}, ...     % send 0 to shutdown
          {'RunMode',{4, self.msg_sizes.bsize, 'NULL', 'Set run mode'}}, ...            % send 0 to shutdown
          {'SetFan',{18, 4*self.msg_sizes.dsize, 'NULL', 'Set fan speed'}}, ...          % 4 doubles for each fan voltage
          {'LogMode',{19, self.msg_sizes.bsize, 'NULL', 'Set log record mode'}}, ...
          {'GetSensors',{20, self.msg_sizes.bsize, 'NULL', 'Request sensor reading'}}, ...
          {'EOL',{22, self.msg_sizes.bsize, 'endDataMesg', 'End of sensor log'}},  ...
          {'GetLogRow',{23, self.msg_sizes.dsize, 'NULL', 'Request sensor log data'}}, ...
          {'SetLogRate',{33, self.msg_sizes.dsize, 'NULL', 'Set log sample rate'}}, ...
          {'SensorValues',{63, 15*self.msg_sizes.dsize, 'ReadRawData', 'Sensor readings'}}, ...
          {'LogEntry',{64, 16*self.msg_sizes.dsize, 'ReadRawData', 'Sensor log entry'}}, ...
          {'LogSize',{65, self.msg_sizes.dsize, 'ReadRawData', 'Sensor log size'}}, ...
          {'AckRunMode',{104, self.msg_sizes.bsize, 'ReadAckMesg', 'Ack run mode'}}, ...
          {'AckFan',{118, self.msg_sizes.bsize, 'ReadAckMesg', 'Ack fan volt'}}, ...
          {'AckLogMode',{119, self.msg_sizes.bsize, 'ReadAckMesg', 'Ack sensor log run mode'}}, ...
          {'AckLogRate',{133, self.msg_sizes.bsize, 'ReadAckMesg', 'ACK log sample rate'}} ...
          };
